txt[0] = "Graphics";
txt[1] = "Jan Durkac"
txt[2] = "CODE WRITERS"
txt[3] = "Martin Obert, Petr Kunc, Jan Durkac"
txt[4] = "SOUNDS"
txt[5] = "Petr Kunc"
txt[6] = "BACKGROUND/IMAGES"
txt[7] = "ESA";
txt[8] = "NASA";
txt[9] = "Hubble Heritage Team";
txt[10] = "(STScI/AURA)";
txt[11] = "A. Simon (GSFC)";
txt[12] = "Raghvendra Sahai";
txt[13] = "John Trauger (JPL)";
txt[14] = "WFPC2 science team";
txt[15] = "Andrew Fruchter (STScI) ";
txt[16] = "ERO team (STScI + ST-ECF)";
txt[17] = "Bruce Balick (University of Washington) ";
txt[18] = "Jason Alexander (University of Washington)";
txt[19] = "Arsen Hajian (U.S. Naval Observatory) ";
txt[20] = "Yervant Terzian (Cornell University)";
txt[21] = "Mario Perinotto (University of Florence, Italy)";
txt[21] = "Patrizio Patriarchi (Arcetri Observatory, Italy)";
txt[21] = "© All rights reserved 2018";

count = 22; // pocet textu
a = 0; // Nechat tak.
alarm[0] = 75;